### ISSUE TITLE
Guide to apply patches

### ISSUE THREAD

**Issue by saschanaz** [kitakar5525/linux-surface-patches#2]
First, big thank you for distributing your patches!

I tried applying those patches as I just installed Ubuntu 20.04 on my Surface 3, but it seems there is no `drivers/platform/x86/Kconfig` in my `/lib/modules/5.4.0-26-generic/kernel` directory. Could you give me some guide how to solve this problem? Thanks!

**Comment by kitakar5525** [comment]
Hello! I'm glad you're interested in those patches :)

First, I want to confirm that what's your goal?
- If your goal is just to run patched kernel for Surface 3:
  Have you already tried linux-surface kernels? (https://github.com/linux-surface/linux-surface)
  Both 4.19 LTS kernel and the latest stable 5.6 kernel run well on Surface 3.
  Currently, patches in my repo are largely the same as linux-surface (the addition is only debug patches currently).
- If your goal is to build kernel by yourself, then let me know. I'll provide additional info later.
  I use Arch Linux but for debian-based distros, this entry may be helpful: https://github.com/jakeday/linux-surface#for-debian-based-systems

**Comment by kitakar5525** [comment]
Regarding the `Kconfig` missing issue itself, have you installed `linux-headers` package?

**Comment by saschanaz** [comment]
Ah, my goal is to just run it. I'll try the kernels, thanks!

**Comment by kitakar5525** [comment]
OK, so I'm closing this issue. Let me know if you need more info :)

**Comment by kitakar5525** [comment]
oh, leaving a note here that linux-surface also has wiki entry for building kernel for Debian-based distros: https://github.com/linux-surface/linux-surface/wiki/Compiling-the-Kernel-from-Source
